services:
  main-service:
    image: main-service-project-iso
    container_name: main-service-project-container
    ports:
      - "8888:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MainServiceDataBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NURIK2005
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
