
services:
  main-service:
    image: main-service-project-iso
    container_name: main-service-project-container
    ports:
      - "8888:8080"
    depends_on:
      - postgres
      - keycloak

  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: MainServiceDataBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NURIK2005
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    command:
      - start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/MainServiceDataBase
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=NURIK2005
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  app-postgres: # Новый сервис базы данных для самого приложения
      image: postgres:17.2
      environment:
        POSTGRES_DB: AppCourseDataBase  # Название базы данных для приложения
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: NURIK2005
      ports:
        - "5433:5432"  # Используем другой порт для второго контейнера PostgreSQL
      volumes:
        - app_postgres_data:/var/lib/postgresql/data  # Новый том для хранения данных приложения

volumes:
  postgres_data:
  app_postgres_data:
